export const ACCOUNT_PROFILE_STATE_KEY = 'account';

export const SUBMIT_ACCOUNT_LOGIN = 'ATR/ACCOUNT_LOGIN/SUBMIT_ACCOUNT_LOGIN';
export const SUBMIT_ACCOUNT_LOGIN_SUCCESS =
  'ATR/ACCOUNT_LOGIN/SUBMIT_ACCOUNT_LOGIN_SUCCESS';
export const SUBMIT_ACCOUNT_LOGIN_ERROR =
  'ATR/ACCOUNT_LOGIN/SUBMIT_ACCOUNT_LOGIN_ERROR';
export const SUBMIT_ACCOUNT_LOGOUT = 'ATR/ACCOUNT_LOGIN/SUBMIT_ACCOUNT_LOGOUT';

export const SET_IS_USER_AUTHENTICATED =
  'ATR/ACCOUNT_LOGIN/SET_IS_USER_AUTHENTICATED';
