export const ACCOUNT_PROFILE_STATE_KEY = 'account';

export const SUBMIT_ACCOUNT_LOGIN = 'ATR/ACCOUNT_LOGIN/SUBMIT_ACCOUNT_LOGIN';
export const SUBMIT_ACCOUNT_LOGIN_SUCCESS =
  'ATR/ACCOUNT_LOGIN/SUBMIT_ACCOUNT_LOGIN_SUCCESS';
export const SUBMIT_ACCOUNT_LOGIN_ERROR =
  'ATR/ACCOUNT_LOGIN/SUBMIT_ACCOUNT_LOGIN_ERROR';
export const SUBMIT_ACCOUNT_LOGOUT = 'ATR/ACCOUNT_LOGOUT/SUBMIT_ACCOUNT_LOGOUT';
export const SUBMIT_ACCOUNT_LOGOUT_SUCCESS =
  'ATR/ACCOUNT_LOGOUT/SUBMIT_ACCOUNT_LOGOUT_SUCCESS';
export const SUBMIT_ACCOUNT_LOGOUT_ERROR =
  'ATR/ACCOUNT_LOGOUT/SUBMIT_ACCOUNT_LOGOUT_ERROR';

export const TOGGLE_USER_AUTHENTICATED =
  'ATR/ACCOUNT_LOGIN/TOGGLE_USER_AUTHENTICATED';
