export const ACCOUNT_SIGNUP_STATE_KEY = 'signup';

export const SUBMIT_ACCOUNT_SIGNUP = 'ATR/ACCOUNT_SIGNUP/SUBMIT_ACCOUNT_SIGNUP';
export const SUBMIT_ACCOUNT_SIGNUP_SUCCESS =
  'ATR/ACCOUNT_SIGNUP/SUBMIT_ACCOUNT_SIGNUP_SUCCESS';
export const SUBMIT_ACCOUNT_SIGNUP_ERROR =
  'ATR/ACCOUNT_SIGNUP/SUBMIT_ACCOUNT_SIGNUP_ERROR';
