export const DASHBOARD_AUDIT_STATE_KEY = 'profile';

export const FETCH_PROFILE_DATA = 'ATR/DASHBOARD/FETCH_PROFILE_DATA';
export const FETCH_PROFILE_DATA_SUCCESS =
  'ATR/DASHBOARD/FETCH_PROFILE_DATA_SUCCESS';
export const FETCH_PROFILE_DATA_ERROR =
  'ATR/DASHBOARD/FETCH_PROFILE_DATA_ERROR';
