export const PROJECT_AUDIT_STATE_KEY = 'projectAudit';

export const GET_PROJECT = 'ATR/PROJECT_AUDIT/GET_PROJECT';
export const GET_PROJECT_SUCCESS = 'ATR/PROJECT_AUDIT/GET_PROJECT_SUCCESS';
export const GET_PROJECT_ERROR = 'ATR/PROJECT_AUDIT/GET_PROJECT_ERROR';
