export const CREATE_AUDIT_STATE_KEY = 'createAudit';

export const SUBMIT_CREATE_AUDIT = 'ATR/CREATE_AUDIT/SUBMIT_CREATE_AUDIT';
export const SUBMIT_CREATE_AUDIT_SUCCESS =
  'ATR/CREATE_AUDIT/SUBMIT_CREATE_AUDIT_SUCCESS';
export const SUBMIT_CREATE_AUDIT_ERROR =
  'ATR/CREATE_AUDIT/SUBMIT_CREATE_AUDIT_ERROR';

export const CLEAR_CREATE_AUDIT_DATA =
  'ATR/CREATE_AUDIT/CLEAR_CREATE_AUDIT_DATA';

export const GET_PROJECT_DOMAINS = 'ATR/CREATE_AUDIT/GET_PROJECT_DOMAINS';
export const GET_PROJECT_DOMAINS_SUCCESS =
  'ATR/CREATE_AUDIT/GET_PROJECT_DOMAINS_SUCCESS';
export const GET_PROJECT_DOMAINS_ERROR =
  'ATR/CREATE_AUDIT/GET_PROJECT_DOMAINS_ERROR';
