export const CREATE_AUDIT_STATE_KEY = 'createAudit';

export const SUBMIT_CREATE_AUDIT = 'ATR/CREATE_AUDIT/SUBMIT_CREATE_AUDIT';
export const SUBMIT_CREATE_AUDIT_SUCCESS =
  'ATR/CREATE_AUDIT/SUBMIT_CREATE_AUDIT_SUCCESS';
export const SUBMIT_CREATE_AUDIT_ERROR =
  'ATR/CREATE_AUDIT/SUBMIT_CREATE_AUDIT_ERROR';

export const CLEAR_CREATE_AUDIT_DATA =
  'ATR/CREATE_AUDIT/CLEAR_CREATE_AUDIT_DATA';

export const CREATE_QUESTIONNAIRE_SET =
  'ATR/CREATE_AUDIT/CREATE_QUESTIONNAIRE_SET';
export const CREATE_QUESTIONNAIRE_SET_SUCCESS =
  'ATR/CREATE_AUDIT/CREATE_QUESTIONNAIRE_SET_SUCCESS';
export const CREATE_QUESTIONNAIRE_SET_ERROR =
  'ATR/CREATE_AUDIT/CREATE_QUESTIONNAIRE_SET_ERROR';

export const GET_PROJECT_CATEGORIES = 'ATR/CREATE_AUDIT/GET_PROJECT_CATEGORIES';
export const GET_PROJECT_CATEGORIES_SUCCESS =
  'ATR/CREATE_AUDIT/GET_PROJECT_CATEGORIES_SUCCESS';
export const GET_PROJECT_CATEGORIES_ERROR =
  'ATR/CREATE_AUDIT/GET_PROJECT_CATEGORIES_ERROR';
